/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newsystem;

import javax.swing.JOptionPane;
import java.beans.PropertyVetoException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author JaiShriRam
 */
public class DesktopForm extends javax.swing.JFrame {

    boolean flagChangePassword, flagSelectMonth, flagSelectDuration, flagSelectYear, flagSheetFI, flagSheetFE,
            flagSheetMI, flagSheetME = true;
    FrmChangePassword cp = new FrmChangePassword();
    FrmFillMovInt fs = new FrmFillMovInt();
    FrmFillMovExt filExt = new FrmFillMovExt();
    FrmFillStrip fill = new FrmFillStrip();
//    FrmSelectYear frmYear = new FrmSelectYear();
//    FrmSelectDuration frmSix = new FrmSelectDuration();
    FrmSelectMonth frmMonth = new FrmSelectMonth();
    FrmFillFixInt frmFixInt = new FrmFillFixInt();
//    FrmFillFixExt frmFixExt = new FrmFillFixExt();
//    FrmViewMonth fvm = new FrmViewMonth();

    /**
     * Creates new form DesktopForm
     */
    public DesktopForm() {
//        Desktop.add(fvm);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuFillSheet = new javax.swing.JMenu();
        mnuMovStrip = new javax.swing.JMenu();
        mnuMovInt = new javax.swing.JMenuItem();
        mnuMovExt = new javax.swing.JMenuItem();
        mnuFixExt = new javax.swing.JMenuItem();
        mnuAddStrip = new javax.swing.JMenu();
        mnuView = new javax.swing.JMenu();
        mnuViewMonth = new javax.swing.JMenuItem();
        mnuChangePwd = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPS Calculator v1.0");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1035, 539));
        setName("RPS - Calculator  ( Home )"); // NOI18N
        setSize(new java.awt.Dimension(1200, 700));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Desktop.setForeground(new java.awt.Color(204, 255, 255));
        Desktop.setToolTipText("");
        Desktop.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Desktop.setMinimumSize(new java.awt.Dimension(1035, 539));
        Desktop.setLayout(new java.awt.CardLayout());
        getContentPane().add(Desktop);

        mnuFillSheet.setText("Fill Sheet");

        mnuMovStrip.setText("Movable Strip");

        mnuMovInt.setText("Internal Sheet");
        mnuMovInt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuMovIntMousePressed(evt);
            }
        });
        mnuMovInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovIntActionPerformed(evt);
            }
        });
        mnuMovStrip.add(mnuMovInt);

        mnuMovExt.setText("External Sheet");
        mnuMovExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuMovExtMousePressed(evt);
            }
        });
        mnuMovStrip.add(mnuMovExt);

        mnuFillSheet.add(mnuMovStrip);

        mnuFixExt.setText("Fixed Strip ");
        mnuFixExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuFixExtMousePressed(evt);
            }
        });
        mnuFixExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFixExtActionPerformed(evt);
            }
        });
        mnuFillSheet.add(mnuFixExt);

        mnuBar.add(mnuFillSheet);

        mnuAddStrip.setText("Add Strips");
        mnuAddStrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuAddStripMousePressed(evt);
            }
        });
        mnuAddStrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddStripActionPerformed(evt);
            }
        });
        mnuBar.add(mnuAddStrip);

        mnuView.setText("ViewData");

        mnuViewMonth.setText("Month Wise");
        mnuViewMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewMonthActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewMonth);

        mnuBar.add(mnuView);

        mnuChangePwd.setText("Change Password");
        mnuChangePwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuChangePwdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuChangePwdMousePressed(evt);
            }
        });
        mnuChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePwdActionPerformed(evt);
            }
        });
        mnuBar.add(mnuChangePwd);

        mnuLogOut.setText("Log Out");
        mnuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLogOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuLogOutMousePressed(evt);
            }
        });
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        mnuBar.add(mnuLogOut);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMovIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMovIntActionPerformed

    private void mnuViewMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewMonthActionPerformed
        try {
            if (!frmMonth.isVisible()) {
                Desktop.add(frmMonth);
                frmMonth.setVisible(true);

                frmMonth.setSelected(true);
                frmMonth.moveToFront();
            } else {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");

                frmMonth.setSelected(true);
                frmMonth.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuViewMonthActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
//        System.exit(0);

    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePwdActionPerformed
//        try {
//            if (cp.isVisible()) {
//                JOptionPane.showMessageDialog(null, "This Window is already opened...");
//                cp.moveToFront();
//                cp.setSelected(true);
//            } else {
//                cp.setVisible(true);
//                Desktop.add(cp);
//                cp.moveToFront();
//                cp.setSelected(true);
//            }
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_mnuChangePwdActionPerformed

    private void mnuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMouseClicked
//        System.exit(0);
    }//GEN-LAST:event_mnuLogOutMouseClicked

    private void mnuChangePwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuChangePwdMouseClicked
    }//GEN-LAST:event_mnuChangePwdMouseClicked

    private void mnuChangePwdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuChangePwdMousePressed
        try {
            if (cp.isVisible()) {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");

                cp.setSelected(true);
                cp.moveToFront();
            } else {
                Desktop.add(cp);
                cp.setVisible(true);
                cp.setSelected(true);
                cp.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuChangePwdMousePressed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void mnuLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogOutMousePressed
        System.exit(0);
    }//GEN-LAST:event_mnuLogOutMousePressed

    private void mnuAddStripMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAddStripMousePressed
        try {
            if (fill.isVisible()) {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");

                fill.setSelected(true);
                fill.moveToFront();
            } else {
                Desktop.add(fill);
                fill.setVisible(true);
                fill.setSelected(true);
                fill.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuAddStripMousePressed

    private void mnuMovIntMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMovIntMousePressed
        try {
            if (!fs.isVisible()) {
                Desktop.add(fs);
                fs.setVisible(true);

                fs.setSelected(true);
                fs.moveToFront();
            } else {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");

                fs.setSelected(true);
                fs.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuMovIntMousePressed

    private void mnuMovExtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMovExtMousePressed
        try {
            if (!filExt.isVisible()) {
                Desktop.add(filExt);
                filExt.setVisible(true);

                filExt.setSelected(true);
                filExt.moveToFront();
            } else {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");

                filExt.setSelected(true);
                filExt.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuMovExtMousePressed

    private void mnuFixExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFixExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuFixExtActionPerformed

    private void mnuFixExtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuFixExtMousePressed
        try {
            if (!frmFixInt.isVisible()) {
                Desktop.add(frmFixInt);
                frmFixInt.setVisible(true);
                frmFixInt.setSelected(true);
                frmFixInt.moveToFront();
            } else {
                JOptionPane.showMessageDialog(null, "This Window is already opened...");
                frmFixInt.setSelected(true);
                frmFixInt.moveToFront();
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuFixExtMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        URL url = getClass().getResource("");
        ImageIcon img = new ImageIcon("src\\newsystem\\PITechLogo.png");
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void mnuAddStripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddStripActionPerformed
//        try {
//            if (fill.isVisible()) {
//                JOptionPane.showMessageDialog(null, "This Window is already opened...");
//                fill.moveToFront();
//                fill.setSelected(true);
//            } else {
//                fill.setVisible(true);
//                Desktop.add(fill);
//                fill.moveToFront();
//                fill.setSelected(true);
//            }
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(DesktopForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_mnuAddStripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DesktopForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu mnuAddStrip;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuChangePwd;
    private javax.swing.JMenu mnuFillSheet;
    private javax.swing.JMenuItem mnuFixExt;
    private javax.swing.JMenu mnuLogOut;
    private javax.swing.JMenuItem mnuMovExt;
    private javax.swing.JMenuItem mnuMovInt;
    private javax.swing.JMenu mnuMovStrip;
    private javax.swing.JMenu mnuView;
    private javax.swing.JMenuItem mnuViewMonth;
    // End of variables declaration//GEN-END:variables
}
